etc/infrasim.conf.example
infrasim/vm.py

@MarkMa001 @xiar @fub2 @PaynePei @turtle-fly 
It passed all functional tests. Qemu mac is different between different compute node in same EXSI. Will automatically load same mac after reboot/powercycle a compute node. Supports up to 8 mac for same qemu.

HWSIM-854, fix QEMU MAC addresses are the same.

---

.unittests
infrasim/qemu.py
test/unit/test_qemu.py

1. seperate cdrom option alone
2. add set_cdrom/set_kvm unittest
Signed-off-by: Mark <mark.ma@emc.com>

Bugfix for cdrom option in qemu command

---

test/functional/test_ipmi_console.py

Remove the 'Terminate' caution at the end of the test_ipmi_console.

---

test/functional/test_ipmi_chassis.py

In the test suit, the following chassis power commands are tested:
- status
- on
- off
- cycle
- reset
Three test cases are implemented:
1) test_chassis_power_off_on:
Before the test, the power status is on. The following commands are executed:
- chassis power off
- chassis power on
After each action, the chassis status and qemu status are checked.
2) test_chassis_power_cycle:
Before the test, the power status is on. The pid of qemu is stored, then run
- chassis power cycle
- sleep 1.5s
- compare new pid with old pid of qemu
The pid should be different after power cycle.
3) test_chassis_power_reset:
Similar to power_cycle.

Add functional test 'test_ipmi_chassis.py' in this commit.

---

infrasim/init.py

Some libraries cannot be found without this command, which will result in ipmi_sim failure.

Add ldconfig command back to init

---

infrasim/ipmicons/common.py
test/functional/test_ipmi_console.py

- Get vBMC credential from IPMI SIM for user when running ipmitool command
- Fix the test_ipmi_console function test errors
error messages:
===
-------------------- >> begin captured logging << --------------------
root: INFO: socat start
root: DEBUG: ipmi_sim -c /home/robert/.infrasim/node-0/data/vbmc.conf -f
/home/robert/.infrasim/node-0/data/quanta_d51.emu -n -s /var/tmp
root: INFO: bmc start
ipmi_sim: ERROR: Unable to connect lanserv at 9000: [Errno 111]
Connection refused
--------------------- >> end captured logging << ---------------------

Get vbmc credential from ipmi_sim real time and update functional test

---

infrasim/model.py
test/functional/test_configuration_change.py

Add 'fork' for socat, since if connecting socat multiple times, the socat will fail

[BUGFIX] fix socat exits unexpectedly

---

infrasim/model.py
test/functional/test_cli_commands.py

*  Add '-kernel' and '-initrd' parameters
*  Fix the functional testing issue if users don't install infrasim-compute
when running function testing

Add kernel and initrd parameters 

---

bin/racadmsim
etc/infrasim.full.yml.example
infrasim/init.py
infrasim/model.py
infrasim/racadm.py
infrasim/racadmsim.py
infrasim/repl.py
setup.cfg

Added module infrasim.repl
Implemented iDRAC SSH simulation, with command `racadm` to go
to racadm console
Check how `RacadmConsole` inherits `REPL` and how it be used in another ssh service:
racadm = RacadmConsole()
racadm.set_input(self.repl_input)
racadm.set_output(self.repl_output)
racadm.run()
How to try this implementation:
1. Go to infrasim code folder
2. Run server with:
sudo python -m infrasim.racadm
3. Start another SSH session with putty for example, to connect to port `10022`

A easy to extend REPL and RACADM console with the REPL

---

bin/racadmsim
infrasim/model.py
infrasim/racadmsim.py

Two behaviors to simulate in this patch:
- in racadm REPL, it echo command then print result
- in racadm REPL, it ignores a redundant prefix racadm, so when
you type `racadm getled`, you are actually running `getled`

Simulate racadm console behavior

---

infrasim/racadmsim.py

Previously, when racadm server listen to inline SSH command, it
output with the method `channel.send`. This is a method returns
data in a certain length. If data is too long, some data will
get lost.
Now this output is changed to `channel.sendall`. Per [paramiko's
documentation](http://paramiko-docs.readthedocs.io/en/latest/api/channel.html#paramiko.channel.Channel.sendall), `sendall` will send all data until it's finished.

Inline SSH now gets all response data

---

infrasim/cli.py
infrasim/helper.py
infrasim/ipmi.py
infrasim/model.py
infrasim/qemu.py
infrasim/socat.py

Add check in Namespace __init__ to check if network namespace exists. If not, raise InfraSimError.
Catch namespace error in cli command handler and add it to error log in ipmi, qemu, socat start functions.

Catch namespace doesn't exist exception

---

infrasim/helper.py
infrasim/model.py
test/functional/test_configuration_change.py
test/functional/test_racadm.py
test/unit/test_model.py

- Remove useless log in helper
- Remove the netifaces used by test code
- Make the functional testing work without installation
---
Add qemu parameters "--append"
Add this 'cmdline' in ymal configuration as below:
...
compute:
...
- cmdline: "..."
this will make qemu to generate the command line qemu-system-x86_64 ...
--append "..."
---
Test racadmsim without installation

Remove netifaces from test and enhance testing 

---

setup.py
template/version.yml

Since we use pbr package to handle the versioning scheme, pbr will do the following steps when we setup or package:
1. Check setup.cfg to see if version is set.
2. Read tags in local git to retrieve the latest version tag.
3. Compare the version number in setup.cfg with the latest tag.
a. If no version is set in setup.cfg:
a.a if no version tag is found in "git tag", package version = 0.0.1.dev{total commit number}
a.b if version tag is found in "git tag":
a.b.a if version tag is tagged on the latest commit, package version = this number.
a.b.b if version tag is tagged on an old commit, package version = {version tag number}.dev{latest commit number - tag commit number}.
b. If version is set in setup.cfg
b.a if no version tag is found in "git tag", package version = {version in …

Remove setup.cfg version writing from setup.py

---

etc/infrasim.full.yml.example
infrasim/model.py
infrasim/qemu.py
infrasim/socat.py
test/functional/test_configuration_change.py
test/functional/test_main_intf.py
test/functional/test_node_ports.py
test/functional/test_serial.py
test/unit/test_model.py

Previously, infrasim use port 9003 by default to forward serial
stream. This leads critical hang on some cloud environment.
Now this is changed to use UNIX socket, and impacts socat and
qemu with the command line option like this:
- socat, `unix-listen:<socket_file>`
- qemu, `-chardeve,socket,path=<socket_file>`
Added test on SOL to verify this data path is available.

Use UNIX socket for serial

---

infrasim/helper.py
infrasim/model.py
test/functional/test_start_stop.py

`Double fork` to start core process to make them managed by init
process and can be collected once killed.
Previously, if you run some appliance to call infrasim library,
call CNode.stop() to stop your core process, the process can't be
collected normally, which leads to following failure to start new
instances.
Reference of the double fork solution:
[Stack: os.kill(pid, SIGTERM) is causing my process to become a zombie](http://stackoverflow.com/questions/22815514/python-os-killpid-sigterm-is-causing-my-process-to-become-a-zombie)
[Stack: Run python program, have it continue to run after script is killed](http://stackoverflow.com/questions/6011235/run-a-program-from-python-and-have-it-continue-to-run-after-the-script-is-kille)
[Stack: What happends when sending SIGKILL to a Zombie Process …

Fix core process become zombie in nosetest

---

test/functional/test_with_bridge.py

ipmi_sim needs time to set lan configuration using lancontrol. If it's accessed before setting is done, "lan print" command would fail.
**Temporarily solution:** sleep 2s after node is up.

Bugfix: BMC interface binding remote lan test randomly fails

---

infrasim/__init__.py
infrasim/version.py
template/version.yml

Previously we have two places for version:
1. version num inside infrasim/version.yml
2. version tag on certain commit in .git
To avoid redundancy and easier to maintain version, we can use
pkg_resources library in setuptools to fetch infrasim-compute version
from working set.
However, this method has a problem:
If you installed several versions of infrasim-compute without
uninstalling the old ones, the version will show the largest version you
installed, not the latest one.
Haven't found solution yet.

Change version checking for infrasim

---

infrasim/cli.py
infrasim/config_manager.py
test/functional/test_cli_commands.py

Added command line `infrasim config edit <name>` to start an
editor interaction on configuration of node <name>.
It reads user's `EDITOR` from envionroment. If it's not set,
`vi` will be opened as a default editor.
Added test on InfraSIM command line navigation.

Enable `infrasim config edit`

---

etc/infrasim.full.yml.example
infrasim/model.py
test/unit/test_model.py

Model:
Now recognize `use_jbod` and `use_msi` defined in yml.
Example:
`max-sge` is fixed to `max_sge`.
Added unit test for controller's attributes and drive's attributes.
Verify they can be well collected to qemu command line option.

Fix controller drive attributes error

---

infrasim/model.py

if CharDev is used as a server, it do not need attribute reconnect since server will not connect initiatively.

set-server-reconnect-None

---

infrasim/model.py

boot_param is set to be a list but later assigned a str, which result in
failure when calling append.
caught by CI T97939.
Error reproduce:
```
sudo infrasim node start
ipmitool -U admin -P admin -H <bmc intf> chassis bootdev disk
ipmitool -U admin -P admin -H <bmc intf> chassis power reset
```
You can see qemu is dead.
Try to restart service by
`sudo infrasim node restart` would fail, see openipmi log:
``` 
File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1547, in handle_parms
boot_param.append("order={}".format(self.__boot_order))
AttributeError: 'str' object has no attribute 'append'
```

Bugfix: param parsing in boot_param

---

infrasim/cli.py
infrasim/global_status.py
test/functional/test_cli_commands.py

#1. add "infrasim global status" command
this cmd will list all the nodes information in the workspace, including all the process it has and all 
the ports it occupied. 
2. add a test for this command

add-global-status-cmd

---

infrasim/model.py
test/functional/test_cli_commands.py
test/functional/test_configuration_change.py
test/functional/test_ipmi_console.py
test/functional/test_ipmi_kcs_smbios.py
test/functional/test_main_intf.py
test/functional/test_node_ports.py
test/functional/test_serial.py
test/functional/test_start_stop.py
test/functional/test_storage.py
test/functional/test_version_command.py
test/functional/test_with_bridge.py

1. Donot set default value for l2-cache-size and refcount-cache-size,  since 
not all of images support the attributes
2. Make pylint happy.

Donnot set default value for l2-cache-size and refcount-cache-size.

---

infrasim/global_status.py
infrasim/helper.py
test/functional/test_cli_commands.py
test/functional/test_configuration_change.py
test/functional/test_ipmi_kcs_smbios.py
test/functional/test_storage.py
test/functional/test_with_bridge.py

In global status command, port occupation will be checked under each
process, however some of them are not ready to listen when the services
just start.
In this case, we have to poll to check when the ports start to listen.
It's not a good way to write a loop everywhere this kind of polling is
used, so we decide to define a try_func function to reduce redundancy.
def try_func(times, func, *args, **kwargs)
"""
times: maximum trials to call the function
func: the function to call
*args: no keyword bounded arguments
**kwargs: keyword bounded arguments
return: function return value or None
"""
If it still fails after *times* calls, this method will raise an
Exception.

Bugfix: global status randomly fails

---

infrasim/config_manager.py

if run command:
sudo infrasim config add node1 ~/node1.yml
it will show hints:
Node node1's configuration already in InfraSIM mapping.
If you want to update the configuration, please run this command:
infrasim **node** update node1 /home/infrasim/node1.yml
here the **node** should be **config**

Fix-wrong-hint-msg

---

infrasim/ipmiconsole/__init__.py
infrasim/ipmiconsole/common.py
infrasim/model.py
test/functional/test_ipmi_console.py
test/functional/test_node_ports.py

Create another thread to monitor if ipmi_sim is still running, if not, call
stop() method from ipmi-console to stop ipmi-console service.

Stop ipmi-console when ipmi_sim stops

---

infrasim/model.py

When qemu call device_del, it needs a device ID.

Add device ID for drive device

---

infrasim/cli.py

if  a user edits the node config file and this node workspace exits,  warn user to destroy node, then this edit will work.

add hint msg after edit node config file when node workspace exits

---

infrasim/helper.py
infrasim/model.py
infrasim/racadmsim/model.py
template/racadmsim/hwinventory_storage_drive_scsi.j2
template/racadmsim/macros.j2
template/racadmsim/storage_drive_scsi.j2
test/functional/test_node_ports.py
test/unit/test_model.py

Support two monitor mode `readline` and `control`.
Do init and precheck according to monitor mode.
Added unit test for CMonitor

Refine CMonitor

---

test/functional/test_ipmi_kcs_smbios.py

Expanded `banner_timeout` for a paramiko client connection, from
15s to 300s.
*Background*
- **SSH banner** returns SSH version information from server to client,
which is used as a reference to config runtime client behavior.
This is caused by SSH1/SSH2 differetiation.
- Lots of cases googled report SSH banner timeout exception,
happening randomly, to well configured SSH server from paramiko
client.
- Paramiko sets a 15s timeout to read the first banner data
from socket (`packtizer` in paramiko). This is the very beginning
of data transfer, even **before handshake**, when resource could
possibly not ready from server's side. So it leads below errors
in infrasim kcs test.
- Since paramiko 1.15, `client.connect` added the parameter
`banner_timeout` for user to set the first timeout to get …

Fix banner timeout exception in kcs test

---

infrasim/model.py
test/unit/test_model.py

1. model.py raised exception if "kvm_enabled" was not defined in yml,
it is now well handled.
2. added protection if "kvm_enabled" is not boolean
3. refine code convention in test

Hotfix on kvm_enable feature

---

infrasim/helper.py
infrasim/model.py
test/fixtures.py
test/functional/test_configuration_change.py
test/functional/test_scsi_page.py
test/unit/test_helper.py
test/unit/test_model.py

For NVMe option `cmb_size_mb`, we customize test to be run only
on qemu version `>=2.10`. This feature is implemented by a
decorator in infrasim.helper.
Move concrete behavior and attribute of IDEDrvie and SCSIDrive
to their derived class, instead of being in CBaseDrive. Based on
this, we provide NVMeController as a derived class from
CBaseDrive.
**kind of weird**...but we decided to make NVMeController inherits
CBaseDrive instead of CBaseStorageController, due to it needs a
drive backend.
Signed-off-by: bcyan <448162474@qq.com>

Added NVMe support

---

infrasim/ipmiconsole/__init__.py

When a user tries to stop an ipmi-console instance which is not running,
it will try to find the process in ps and get pid "", then try to
convert it to int, then fail with message "invalid literal for int()
with base 10: ''".

Fix stop a stopped ipmi-console raised exception

---

infrasim/__init__.py
infrasim/model.py
test/unit/test_model.py

Added `share-rw` support for block device, which can be parsed
as an attribute of CBaseDrive. It's expected to be a boolean,
which means you need to specify `true`, `false`, `on`, `off` in yml.
Added type protection and unit test on `share-rw`.
Record log and stack for any InfraSimError, so developers won't
have to write one line to log and one line to raise exception.
Now only raise statement is needed.

Enable share-rw for block device

---

infrasim/ipmiconsole/__init__.py
infrasim/model.py
test/functional/test_ipmi_console.py
test/functional/test_scsi_page.py

How ipmi-console stop after vBMC stop:
- At first, ipmi-console starts a `monitor thread` from main thread
- Monitor thread is in charge of monitoring vBMC alive status,
once vBMC process stops, it go to a `stop` procedure, which sends
SIGTERM then set a global `quit_flag`
- Above monitor is a polling in a `3s` cadence, and needs scheduling,
and resource release
Test with 5s in cleaning stage randomly fails. See what's going on
with 10s in cleaning stage.

Fix ipmi console test failure

---

infrasim/monitor/__init__.py
requirements.txt

1. Monitor service relies on flask/flask-restplus, so add them into requirements.txt.
2. Fix type error, feed int type to parameter of flask app port. 
3. Dos2unix for monitor init file.

Hot Fix for mointor service start issues

---

infrasim/package_install.py

We used to hard code version number, which requires to upgrade the number upon newer version. 
So here we can automate searching for the greatest version number.
@InfraSIM/infrasim_dev @fub2 @chenc52 @xiar @chenge3

In package install, automate searching for the greatest version number

---

infrasim/helper.py
test/functional/test_host_io.py
test/functional/test_ipmi_kcs_smbios.py
test/functional/test_sas.py
test/functional/test_storage.py
test/functional/test_with_bridge.py

@InfraSIM/infrasim_dev @xiar @chenc52 @chenge3 @XiaowenJiang @fub2    
1. For test_sas.py:
Change port forward for connetion to monitor from telnet to UnixSocket
2. Put port_forward() function into common model, and called by all tests need the function.
3. Put prepare_ssh function into common model, and called by all tests need the function.

test/function: change port forward connection from telnet to UnixSocket

---

test/functional/test_pcie_topo.py

NVME device ID was changed in QEMU which makes test_nvme_bdf in pcie topo test failed in CI.
QEMU commit:
hw/block/nvme: fix the write issues
commit: f9db947c656caa06e8ad58078a1798ae7f695800

hotfix: test pcie topo - nvme device id

---

infrasim/cli.py

The command "infrasim node info" suppose each node's storage_backend type is driver.
So if the storage_backend type is disk_array or connectors, the program go wrong.
I add some "if" to judge the type and then print the node info.

Fix the command 'infrasim node info'

---

test/functional/test_start_stop.py

To stress test for node start stop continuously for 5 times.

To stress test for node start stop.

---

infrasim/colors.py
infrasim/filelock.py
infrasim/global_status.py
infrasim/model/core/task.py
test/functional/test_cli_commands.py

1. add colors for highlighting the task pid
2. add filelock for accessing task pid file
the filelock module is copied from
https://github.com/benediktschmitt/py-filelock
The license is under public domain, see more license info here:
https://github.com/benediktschmitt/py-filelock/blob/master/LICENSE.rst
3. using 'lsof' to query listening ports instead of 'netstat'
Originally, it's using helper.try_func to run the command, if fails,
then it will retry 600 times of this command, it's not reasonable to
to try so many times, since if there is no port listening on for this
process, then this command will fail, just ignore it and check next process
4. update the tests since the CLI command output is changed
format all the CLI output, and highlight the process id for start(green) and stop(red)

colors, filelock, tasks, global status and tests changes.

---

infrasim/model/tasks/bmc.py
template/vbmc.conf

1.add gem_enable in bmc in yaml:
bmc:
gem_enable: True
2.modify the template of vbmc.
make the workspace fold depend on gem_enable.

bug fix: vbmc.conf can not support legacy openipmi

---

infrasim/model/core/task.py
infrasim/model/tasks/bmc.py
infrasim/model/tasks/compute.py
template/vbmc.conf

for enabling peer BMC, add the following attributes in YAML config:
compute:
....
bmc:
...
peer-bmcs:
- addr: 0x1e
user: "test"
password: "test"
interface: "lanplus"
host: "10.62.59.xx"
- addr: 0x1c
...
...
Note: all the attributes are required to access peer BMC, default
the peer bmc is disabled.

infrasim/model: add peer bmc support

---

requirements.txt

1. Current nosetests framework only support to exclude test file/pattern matched test function, but not supporting to exclude test class. 
So here add nose-exclude plugin to support excluding test class from test directory.
2. This is also for enabling jenkins job to exclude test on condition.
@chenge3 @xiar @XiaowenJiang

Add nose-exclude plugin.

---

infrasim/config.py
infrasim/ipmi.py
infrasim/log.py
infrasim/model/__init__.py
infrasim/model/core/node.py
infrasim/model/elements/__init__.py
infrasim/model/elements/trace.py
infrasim/model/tasks/compute.py
infrasim/qemu.py
infrasim/workspace.py

add the following configuration to enable the trace:
compute:
trace:
guest: 'on'
seabios: 'on'
the default log will be at /var/log/<node name>/{seabios.log, guest.log}

infrasim: add trace for seabios and guest os

---

test/functional/test_ipmi_kcs_smbios.py

manufacturer and product name is not ready yet
1. delete smbios test until R630 is ready
2. don't increase skip/error count for the test that environment isn't ready

test: R630 test print error

---

infrasim/model/elements/storage_diskarray.py

Correct phy_map in enclosure definition is very important, otherwise it can't pass Chameleon's check

diskarray: add slot id for drv link

---

infrasim/model/tasks/bmc.py

If there is already a vbmc.conf under runtime workspace, we don't need
to render a new one with template, since user might change it.
Move configuration file existence check before other scripts check
for a more user-friendly notification.

Check vbmc.conf in workspace before try to render a new one.

---

infrasim/model/core/node.py
infrasim/model/tasks/bmc.py
infrasim/model/tasks/socat.py
test/unit/test_model.py

Currently all nodes use .pty0 for socat, but ipmi_sim will use lock name
as LCK...pty0, so we can only enable sol for one node since ipmi_sim for
other nodes won't be able to pass lock check.

Zhenzan: Fix sol confliction for multiple nodes

---

infrasim/model/core/chassis.py
infrasim/model/elements/__init__.py
infrasim/model/elements/dma_engine.py
infrasim/model/elements/ntb.py
infrasim/model/tasks/compute.py

```
compute:
ntb:
bus: bus_80
addr: '0.0'
bar1_exp: 15
bar2_exp: 15
id: ntb1
peer_id: ntb0         
dma_engine:
id: ioat
addr: '0.0'
bus: 'bus_82'
```

Ntb and ioat parameter support

---

test/functional/test_with_bridge.py

Each test under this class will modify node config then init, no need to render it before the test case (and it will generate a wrong vbmc.conf).

hotfix: remove wrong configuration render

---

test/functional/test_start_stop.py

The serial device has renamed: .pty0 -> .pty0_{node_name}

Bugfix: test_start_stop consistent failure in CI test

---

infrasim/model/tasks/bmc.py
infrasim/model/tasks/socat.py
template/vbmc.conf
test/functional/test_serial.py

1. enable customized vbmc name and use it as name in syslog
2. set unlink-close to 0 because without "unlink-close=0", the link will be deleted when ipmi_sim is restarted or closed which cause SOL cannot be enabled again.

set vbmc name and set unlink-close=0 for ipmi_sim cmdline

---

infrasim/helper.py
test/functional/test_drive_error_inject.py
test/functional/test_sas.py

1. remove '@unittest.skip' instruction since the issue has gone
2. test: nvme redirect stderr to stdout
3. paramiko: remove get_pty attributes since it hangs when there is '*' in command

hot fix in ssh

---

infrasim/model/core/chassis.py
infrasim/model/elements/network.py
infrasim/model/tasks/bmc.py
template/vbmc.conf
test/functional/test_bmc_peer_communication.py

1. According to new ipmb peer connection in openipmi implementation, we don't need <user> <password> <interface> in vbmc.conf, so we remove them in infrasim-compute.
2. Support multiple lan channels in bmc config
example yml:
```
bmc:
address: 32
channels: 1,4
main_channel: 4
peer-bmcs:
- addr: 30
host: xx.xx.xx.xx
port_ipmb: 9009
port_ipmb: 9009
```

Modify ipmb peer interface usage

---

infrasim/model/tasks/bmc.py
test/functional/test_bmc_peer_communication.py
test/functional/test_configuration_change.py

1. Add section to let user pass nvram_file in yml.
2. Skip test cases that are sent through lan/lanplus channel in peer bmc functional test, waiting for the feature to be supported.

Add nvram file customized configuration, skip some peer bmc cases in pr test

---

infrasim/model/core/chassis.py
infrasim/model/elements/drive.py

Check if existing image file size is consistent with 'size' defined in yaml,
if not consistent, will print a warning.

Add drive image size check in drive.py

---

infrasim/model/elements/drive.py
test/functional/test_drive_capacity_consistency.py

1. modify the "WARNING" print in drive-pre-check function
2. add script to check drive capacity consistency
a. expect: yml img size == host img size
b. expect: yml img size == guest img size
c. expect: report failed when access out of range
d. expect: report "WARNING" in runtime log when user specified incorrect img size

add script for drive capacity consistency

---

test/functional/test_drive_capacity_consistency.py

root cause: host can't find the .infrasim/image path
how to fix: get .infrasim path dynamiclly

fix CI test issue, capacity consistency check fail

---

infrasim/chassis/smbios.py
infrasim/model/core/chassis.py
infrasim/model/tasks/compute.py

usage of smbios.py
```
def test_smbios(filename):
bios = SMBios(filename)
chassis_info = {"sn": "hahahaha"}
bios.ModifyType3ChassisInformation(chassis_info)
type2_info = {"sn": "whatever", "location": "spa"}
bios.ModifyType2BaseboardInformation(type2_info)
system_info = {
'sn': "01234456",
"uuid": 'u123456789012345',       # support uuid.UUID() object and string like 'E1A67716-9A01-403C-9A7A-B49F546DD342' as well
'sku_number': '004900080060002D'
}
bios.ModifyType1SystemInformation(system_info)
cpu = {"cores": 4,
"version": "Intel(R) Xeon(R) Silver 4112 CPU @ 2.60GHz",
"sn": "aaaaddd",
"asset_tag": "asset_tag",
"part_number": "part_number",
"speed": 1800,
"max_speed": 4000}
bios.ModifyType4ProcessorInformation(cpu)
dimm = [
{"size": 8 * 1024 * 1024 * 1024,
"manufactuer": "Hynix",
"sn": …
```

smbios: add support to modify Processor, memory device information

---

infrasim/__init__.py
infrasim/chassis/emu_data.py
infrasim/chassis/smbios.py
infrasim/model/core/chassis.py
infrasim/model/tasks/bmc.py
infrasim/model/tasks/compute.py
infrasim/workspace.py
test/unit/test_model.py

Usage in node:
```
node:
bmc:
emu_file: *******
chassis_pn: ****  # automatic set chassis pn to all fru. Overwrite chassis pn in specific fru
chassis_sn: ****   # automatic set chassis sn to all fru. Overwrite chassis sn in specific fru
merge_fru: False
fru2:
chassis:
pn:    *****   # set chassis sn to specific fru unit.    
sn:
board:
pn:
sn:
name:
fru27:
chassis:
pn:
sn:
board:
pn:
sn:
name:
compute:
smbios:
file: ********
type1:  # system information
sn:                 # could be overwritten by compute["serial_number"]
uuid:             #  could be overwritten by compute["uuid"]
sku_number:
type2:  # base board informaiton
sn:
location:
type3:  # chassis information
sn:
type4:  # processor information.
cores:  4
sn: 
type17: # dimm information.
-size: 8G  # slot 0.
sn: *****
pn: **** …
```

Implement function to render smbios and emu data by yml.
