test/functional/test_network.py

@PaynePei @turtle-fly @MarkMa001 @fub2 
Recreate PR, since last PR used default account of infrasim app, which is under name of Mark.
Thanks Payne's comments mentioning the NIC name difference in Ubuntu 14.04, support to 14.04 is now added in script.

Add function test to set qemu to bridge mode. Support Ubuntu 14.04.

---

bin/infrasim-init
bin/infrasim-main
requirements.txt

1. missing qemu roms
2. requirement pip install error

Fix infrasim errors

---

infrasim/qemu.py

Fix qemu disk image file path incorrect issue

---

infrasim/ipmi.py

@xiar @MarkMa001 @fub2 @PaynePei

Fix the bug for ipmi_sim.py

---

bin/infrasim-main
data/script/startcmd
infrasim/qemu.py
infrasim/socat.py

fix qemu mon parameters

---

bin/infrasim-main
data/conf/infrasim.conf
infrasim/console.py
infrasim/ipmi.py
infrasim/qemu.py
infrasim/socat.py

Enable macvtap using qemu command line

---

bin/infrasim-init
bin/infrasim-main
infrasim/__init__.py
infrasim/ipmi.py
infrasim/qemu.py
infrasim/socat.py
test/functional/test_core_process.py
test/functional/test_ipmi_command_response.py

1. run_command will raise exception when command execute failed
2. infrasim-init/infrasim-main will handle exception
3. infrasim/socat.py,qemu.py,ipmi.py will handle exception
4. function test will handle exception

Using exception to handle code routine and return value

---

data/conf/infrasim.conf
infrasim/qemu.py
test/unit/test_qemu.py

Signed-off-by: Mark.Ma<mark.ma@emc.com>

Add cdrom config in infrasim.conf

---

infrasim/console.py
test/functional/test_ipmi_console.py

@sharkconi @PaynePei 
Local test passed.

Add the ipmi console functional test.

---

README.md
bin/infrasim-init
infrasim/qemu.py

Fix SOL no output error

---

README.md
bin/infrasim-init
data/conf/infrasim.conf
infrasim/qemu.py
test/unit/test_qemu.py

Support bridge mode inside qemu, add related unittests

---

test/functional/test_configuration_change.py

@sharkconi @PaynePei 
Local test passed.

Add the configuration change functional test.

---

data/script/chassiscontrol
data/script/resetcmd
data/script/stopcmd
infrasim/qemu.py

1. Add chassis stopcmd/resetcmd to response ipmitool chassis power off/reset
2. Remove macvtap network create/delete function, let user handle it
Signed-off-by:  Mark.Ma <mark.ma@emc.com>

bugfix: ipmitool chassis commmand

---

infrasim/qemu.py

bugfix: fix can't increase disk num issue

---

bin/infrasim-main
data/conf/version.yml
infrasim/__init__.py
test/functional/test_version_command.py

The listed items are:
1. kernel name and release.
2. base OS version.
3. qemu version.
4. openipmi version.
5. socat version.

Add command line to tell Infrasim version

---

README.md
package_install.sh

1. mv libpython installation to manual step 2.format README.md and add setuptools installation

update README.md and package_install script:

---

test/functional/test_version_command.py

Rewrite test_version_command.py

Resubmit test_version_command functional test.

---

infrasim/model.py
test/functional/test_configuration_change.py
test/functional/test_ipmi_chassis.py

Fix Function test failed case

---

test/functional/test_configuration_change.py

Add function test: boot qemu from disk image

---

package_install.sh

@xiar @fub2 @MarkMa001 @XiaowenJiang @turtle-fly

To correct comment symbols.

---

infrasim/main.py
infrasim/model.py
test/functional/test_configuration_change.py

Precheck network mode/name

---

requirements.txt
setup.cfg
setup.py
template/version.yml

1) Read version number from template/version.yml if it's set.
2) Get latest release version as the package version if we choose
to make a release package.

Change setup.py for pypi

---

infrasim/model.py
package_install.sh
test/functional/test_ipmi_kcs.py

Add IPMI KCS function test

---

infrasim/model.py
template/chassiscontrol
test/functional/test_ipmi_command_response.py

Fix infrasim-compute can't change boot order issue
Add boot order function tests
Signed-off-by: Mark.Ma <mark.ma@em.com>

Fix infrasim-compute can't change boot order issue

---

test/functional/test_ipmi_kcs_smbios.py

@fub2 @turtle-fly @MarkMa001 @XiaowenJiang @xiar 
1. Rename test case to reflect test content that adding smbios data verification.
2. Will keep verification for different node types, since it doesn't hurt and may result in better coverage if node type change implemented in future. 
Need design to enable running test case for all types of nodes. It will not be implemented repeatedly in every single test case, but something like a common module which every test case can call.

Add test for SMBIOS data verification.

---

test/functional/test_ipmi_chassis.py
test/functional/test_ipmi_command_response.py

Wait 3s for services fully start.

Add sleep 3s after starting the node.

---

test/functional/test_ipmi_console.py

2016-10-09 07:32:09,640 ERROR Exception in actor
Traceback (most recent call last):
File "/home/robert/github/InfraSIM/infrasim-compute/infrasim/sshim.py",
line 291, in expect
raise EOFError()
EOFError

Fix the error message when running functional test

---

infrasim/helper.py
infrasim/model.py

1) Add helper.py under infrasim/ for useful functions.
2) Check if /dev/kvm exists when no kvm setting is specified in infrasim.yml

Modify kvm setting in CCompute init function

---

setup.py
template/version.yml

And fix the organization name spelling error in version.yml

Change version number to 3.0.0

---

test/functional/test_configuration_change.py
test/functional/test_ipmi_kcs_smbios.py

Check MD5SUM for kcs.img, cirros.img to make sure the image downloaded is complete.

Add MD5 check in functional test

---

etc/infrasim.yml.default

Update default example

---

etc/infrasim.full.yml.example

1. Remove duplicated definition `vnc_display`
2. Change one of network to NAT

Update full example

---

etc/infrasim.full.yml.example

Update full example
1. Remove duplicated definition `vnc_display`
2. Change one of network to NAT

Merge commit 577a1 from infrasim-3.0 branch

---

README.md

Robert smartly found the solution.

Bugfix: README pypi badge display error

---

infrasim/helper.py
infrasim/model.py
infrasim/racadmsim.py
test/functional/test_cli_commands.py
test/functional/test_configuration_change.py
test/functional/test_ipmi_kcs_smbios.py
test/unit/test_model.py

Test racadm works with default config
Test racadm works with configuration setting
Test precheck on conflict port and invalid interface

Enable racadmsim test

---

infrasim/cli.py
infrasim/helper.py
infrasim/ipmi.py
infrasim/model.py
infrasim/qemu.py
infrasim/workspace.py
test/functional/test_net_namespace.py
test/unit/test_core_process.py
test/unit/test_model.py

* Refine CNode __is_running()
* move some code in init_workspace() out to make more flexible
* Running all tasks in namespace if it was enabled
* Running each node in the namespace according to the user setting in yaml configuration file

Misc changes

---

infrasim/ipmi.py
infrasim/ipmicons/common.py
infrasim/model.py
infrasim/workspace.py
test/functional/test_cli_commands.py
test/functional/test_configuration_change.py
test/functional/test_ipmi_console.py

* move the infrasim.yml and vbmc.conf to workspace/etc
* move the script render from class WorkSapce to class CBMC

Move the configuration and scrpt render from workspace to CBMC

---

infrasim/init.py
infrasim/model.py

- Fix the issue of not gettting the correct interfaces
- Remove the netifaces in init.py

Remove netifaces in init.py and fix the issues of not getting correct interfaces

---

infrasim/cli.py
test/functional/test_node_ports.py

1) Add functional test to start 2 nodes with no port conflict.
2) Modify cli.py to display VNC port as config.

Add functional test to run 2 nodes simultaneously on one machine

---

infrasim/racadmsim.py
test/functional/test_racadm.py

Init racadmsim logger, it will record request and response in the path `/var/log/infrasim/<node>/racadmsim.log`

Enable racadm logger

---

infrasim/model.py
test/fixtures.py
test/functional/test_configuration_change.py
test/functional/test_ipmi_kcs_smbios.py

Use new way to create network device for 'NAT' mode instead of legacy way "-net -nic"

 enhancement/use-new-way-to-create-network-interface-for-nat

---

test/functional/test_ipmi_chassis.py

Added test to test infrasim instace keep mac address the same
across power on/off/cycle/reset process.

Add test for persist mac

---

test/functional/test_configuration_change.py
test/functional/test_with_bridge.py

Added test with an unbound bridge:
- Test infrasim start with on network in NAT and another in bridge
- Test infrasim node keep MAC address persistent across chassis
power control

Test infrasim feature with bridge

---

infrasim/helper.py
infrasim/model.py
template/vbmc.conf
test/functional/test_configuration_change.py
test/functional/test_ipmi_console.py
test/functional/test_ipmi_kcs_smbios.py
test/functional/test_with_bridge.py
test/unit/test_model.py

* Modify BMC Binding Rules [ee13385](https://github.com/XiaowenJiang/infrasim-compute/commit/ee1338569ded3f146e50c93ebf9a83afba5be104)
* Add functional test to cover BMC interface binding [7ba7bf2](https://github.com/XiaowenJiang/infrasim-compute/commit/7ba7bf2ae6534fa4b5c8987f60a1eb054d290f24)

Modify BMC interface binding rules

---

etc/infrasim.yml.default
template/infrasim.yml

Now user can use default yml config to start a node.

Fix infrasim example yml file

---

infrasim/model.py
template/vbmc.conf
test/functional/test_configuration_change.py

1. Add param render in vbmc.conf
2. Add related test in test_configuration_change.py

Add BMC LAN channel render for vbmc.conf

---

etc/infrasim.full.yml.example

Fix the format issue in full example YAML file.
@turtle-fly @XiaowenJiang @xiar @WinnieXU1 @fub2

Update etc/infrasim.full.yml.example file

---

etc/infrasim.full.yml.example
etc/infrasim.yml.default

The extra_option is interface for QEMU cli which not supported by InfraSIM.

Add extra_option into full yaml example.

---

infrasim/model.py
test/unit/test_model.py

Update method to select physical cpu to bind:
- Assign a whole core (with all hyper thread processor) first if
requirement is no less than 2
- Assgin scattered processor then
- Ensure all binded processor for one qemu is on the same socket
(or unnecessary context switch may reduce performance)
Pair with @JuneZhou19

Update numactl logic

---

infrasim/model.py
test/fixtures.py
test/functional/test_storage.py

Fix boot index issue in infrasim/model.py.
Add test_storage.py in functional test:
- Add multiple storage controllers/disks configuration test.
- Add boot image test to disk at 1st/2nd/3rd controller separately.

Add storage test in functional test.

---

infrasim/model.py

Reserve first 2 core on each socket, totally 8 thread
for system.

Enhance numactl assignment on 2 socket 10 core

---

infrasim/init.py

Create infrasim.log while execute init without -f.

bugfix/create infrasim.log during init without -f

---

etc/infrasim.yml.default
infrasim/cli.py
infrasim/model.py
test/fixtures.py
test/functional/test_ipmi_console.py
test/functional/test_node_ports.py
test/unit/test_model.py

@fub2 @turtle-fly @chenge3 @XiaowenJiang @xiar @WinnieXU1

Set dell as default node.

---

README.rst

1. Add -f option under "infrasim init".
2. Add edit option under "infrasim config".

Update README for CLI

---

infrasim/cli.py
test/functional/test_storage.py

For HWSIM-1216. @fub2 @xiar @XiaowenJiang @chenge3 @turtle-fly

Function test. Verify if extra ahci controller added to mount drives more than 6

---

infrasim/chassis.py

Usage:
choose to init(or precheck/start/stop) a node by name:
chassis.init(node1, node2, node3, ...)

enhancement: init/start/stop specified nodes by name in CChassis

---

infrasim/model.py

example:
drives:
- size: 8G
l2-cache-size: 67108864  # unit: bytes
　　　refcount-cache-size: 67108864

Add l2-cache-size and refcount-cache-szie for virtual disk (qcow2 format)

---

etc/infrasim.yml.default

@xiar @XiaowenJiang @chenge3 @turtle-fly @WinnieXU1 @fub2

Fix template infrasim yml file, remove controller.

---

test/functional/test_boot.py

Fix issue of getting assertion if machine boots faster. And the removed code is duplicating the section in while loop. So it should be removed.
@xiar @WinnieXU1 @chenge3 @turtle-fly @XiaowenJiang @fub2

Fix issue of getting assertion if machine boots faster. 

---

README.rst

@XiaowenJiang @xiar @chenge3 @fub2 @WinnieXU1 @turtle-fly

Update README.rst, add libaio-dev in apt-get

---

infrasim/cli.py
infrasim/init.py
infrasim/package_install.py
test/functional/test_cli_commands.py

1. Check http get response code.
2. Check fetched file length. If it's zero, there must be something
wrong.
3. Compare hashcode of downloaded file to the file on bintray.
4. If there's any exception during "infrasim init", exit with code 1 instead of just return.

Check downloaded bintray packages in package_install

---

test/unit/test_model.py

@chenge3 @XiaowenJiang @fub2 @turtle-fly @xiar @WinnieXU1

Add unit test for extra option.

---

infrasim/__init__.py
infrasim/cli.py
infrasim/config.py
infrasim/config_manager.py
infrasim/init.py
infrasim/ipmiconsole/__init__.py
infrasim/ipmiconsole/command.py
infrasim/ipmiconsole/common.py
infrasim/log.py
infrasim/model.py
infrasim/qemu.py
infrasim/racadmsim/__init__.py
infrasim/sshim.py

1.add log.py to provide and control the loggers.
2.add command line log to record the command received and the corresponding respond in "/var/log/infrasim.log".
3.change "logger=logging.getLogger()" to "logger=logging.getLogger('logger')", or it will be others' root.

Add-log-in-infrasim.log-and-node-log-space-by-design

---

test/functional/test_host_io.py

@turtle-fly @XiaowenJiang @xiar @chenge3 @WinnieXU1 @fub2 
Add tests for:
1.disk IO across controller, 11 drives, (1 disk is for boot).
2. Verify disk content intact after node restart.

Add kcs io tests and verify disk content after node restart.

---

infrasim/__init__.py
infrasim/package_install.py
test/functional/test_cli_commands.py

Before package installation, it will check if any package exists and will confirm whether to overwrite existing package. 
@chenge3 @turtle-fly @fub2 @XiaowenJiang @xiar

Check if qemu/ipmi/seabios installed before infrasim init.

---

infrasim/model.py

1. Support ESES device
2. Add expander-downstream-phys, expander-upstream-phys, expander-all-phys, expander-count parameters

ESES and expander updates

---

infrasim/model.py
test/unit/test_model.py

1. add page file support in model.py and test_model.py
2. change a duplicated "test_set_scsi_lun"  to "test_set_scsi_slot"

add page file support for drive

---

infrasim/model.py

Add 'force_shutdown' to control how to stop qemu
- force_shutdown: false, then use qemu monitor command "system_powerdown"
to power off the qemu
- else force_shutdown: true, then force the qemu to shutdown with "kill"
Note: if there is no guest OS running, system_powerdown will not work.

Add 'force_shutdown' to control how to stop qemu

---

test/functional/test_host_io.py
test/functional/test_ipmi_kcs_smbios.py
test/functional/test_with_bridge.py

@weia5-emc @chenge3 @chenc52 @turtle-fly @XiaowenJiang @xiar

Update md5 for new kcs.

---

test/functional/test_configuration_change.py
test/functional/test_start_stop.py
test/functional/test_storage.py

@fub2 @turtle-fly @xiar @weia5-emc @XiaowenJiang @chenge3 @chenc52

Remove disk file after test

---

infrasim/model.py

@InfraSIM/infrasim_dev 
related with https://eos2git.cec.lab.emc.com/InfraSIM/qemu/pull/26

add atta_wwn and atta_phy_id support

---

infrasim/model.py
test/functional/test_scsi_page.py

Update msi related qemu option, and update share_rw related func test

---

test/unit/test_model.py

Update megasas related unit test

---

infrasim/helper.py
infrasim/package_install.py
infrasim/version.py
test/functional/test_cli_commands.py
test/functional/test_configuration_change.py
test/functional/test_ipmi_console.py
test/functional/test_scsi_page.py
test/functional/test_version_command.py
test/unit/test_model.py

Update qemu link and version check

---

infrasim/helper.py
infrasim/model/elements/__init__.py
infrasim/model/elements/drive_nvme.py
infrasim/model/elements/fw_cfg.py
infrasim/model/elements/network.py
infrasim/model/elements/pcie_downstream.py
infrasim/model/elements/pcie_rootport.py
infrasim/model/elements/pcie_topology.py
infrasim/model/elements/pcie_upstream.py
infrasim/model/tasks/compute.py

1. support pcie rootport/upstream/downstream modules
2. build pcie topology with pcie_topology
3. support fw_cfg
4. support create pci_topo_fix file
How to build pcie topology:
https://hardware.corp.emc.com/display/HWSIM/PCIE+topology

Enable pcie topology

---

infrasim/dae.py
infrasim/init.py
infrasim/model/elements/backend.py
infrasim/model/elements/storage.py
infrasim/model/elements/storage_lsi.py
test/functional/test_sas.py

1. process disk array definition file
1.1 render disk according to drive template.
1.2 enumerate expanders through hba port connection.
1.3 dump hba link information and drive opts list to json file.
2. add caller in CBackendStorage.init()
3. Change backend.py from CRLF to LF.
Signed-off-by: Julie Jiang <julie.jiang@dell.com>

Enable disk array topology processing

---

infrasim/model/elements/__init__.py
infrasim/model/elements/pcie_downstream.py
infrasim/model/elements/pcie_port.py
infrasim/model/elements/pcie_rootport.py
infrasim/model/elements/pcie_upstream.py

Add a new class: CPCIEPort
CPCIERootport CPCIEUpstream and CPCIEDownstream
inherit CPCIEPort

Refactor pcie topology code

---

infrasim/dae.py
infrasim/model/elements/ses.py
infrasim/model/elements/storage_lsi.py
test/functional/test_sas.py

1. change definition of  ses information.
2. add missing support of ses data.
3. recalculate the number of phys according to change of ses definition.

supplement disk array function support

---

test/fixtures.py
test/functional/test_nvme.py

1. Verify disk count.
2. Write data and read/verify data integrity.
@fub2 @chenc52 @XiaowenJiang @xiar @weia5-emc @chenc52 @bcyan

Add test for nvme disk count verify, and read write verify

---

test/functional/test_with_bridge.py

Add 2.5s delay during ipmi chassis power cycle and off/on test

Hotfix: test with bridge issue

---

test/functional/test_nvme.py

Add nvme id-ctrl test in functional test.

feature/add nvme id-ctrl test

---

test/functional/test_ipmi_chassis.py

Fix qemu process validation and add sleep time 2.5s after qemu starting for openipmi 2.0.24

Fix qemu process validation in test_ipmi_chassis

---

test/fixtures.py
test/functional/test_nvme.py

1. Add NVMe id_ctrl, get_ns_id, get_log, smart_log, error_log and write-zeroes test
2. Refine test_nvme_disk_count
3. Add Ubuntu image checking to skip condition
Signed-off-by: June Zhou <june.zhou@emc.com>

feature/Add test NVMe cases

---

infrasim/config.py
infrasim/model/tasks/bmc.py
infrasim/workspace.py
setup.cfg
test/functional/test_start_stop.py

Signed-off-by: Conghui Chen <conghui.chen@emc.com>

Move ipmi_exec.py to infrasim-compute/scripts

---

infrasim/model/elements/pcie_port.py
infrasim/model/tasks/compute.py
test/unit/test_model.py

1. Fix bug for pcie_topology without sec_bus
2. Add unit test case

BugFix: pcie_topology without sec_bus config

---

infrasim/model/tasks/bmc.py
test/functional/test_ipmi_sim_log.py

Default is record Error Command only to logfile.
To record full log, add:
bmc:
full_log: True
1. logfile: /var/log/infrasim/<nodename>/ipmi_sim.log
2. Add test case for ipmi_sim

Add ipmi_sim logfile: ipmi_sim.log

---

infrasim/model/elements/backend.py
infrasim/model/elements/chassisslot.py

Copy dev_attrs to oem_data.json

---

test/functional/test_nvme.py

Refine test_smart_log regular expression in test nvme

Refine test nvme regular expression

---

infrasim/sshclient.py
test/functional/test_nvme.py

Add nvme tests for get feature/set feature/flush/compare.

---

infrasim/sshclient.py
test/functional/test_nvme.py

Resolve ssh connection issue.

---

test/fixtures.py
test/functional/test_nvme.py

Update ubuntu image path, remind user ubuntu image download url.

---

infrasim/filelock.py
infrasim/sshclient.py

Set paramiko and infraim logger lever to WARNING
@xiar

Set paramiko and infraim logger lever to WARNING

---

test/fixtures.py
test/functional/test_nvme.py

nvme function test, auto-generate bin test files in guest os

---

.gitmodules
test/fixtures.py
test/functional/test_ivn.py

implement ivn test to verify namespace create and delete

implement ivn test to verify namespace create and delete

---

test/functional/test_nvme.py
tox.ini

enable test_infrasim testing with tox

tests: don't create temp file at local when running tests

---

test/functional/test_ivn.py

Refine case assert condition to make it compatible with both
namespace formats: node0ns and node0ns (ID: 0).

Refine test_ivn create and delete namespace

---

infrasim/sshclient.py
test/fixtures.py
test/functional/test_chassis.py
test/functional/test_host_io.py
test/functional/test_nvme.py

Use sshclient to execute commands remotely
Signed-off-by: Robert Xia <robert.xia@emc.com>

Refine case test_copy_file_across_drives

---

test/functional/test_ivn.py

Add switch create and delete in test_ivn

Add switch create and delete in test_ivn

---

infrasim/cli.py
infrasim/config_manager.py
infrasim/model/core/chassis.py
infrasim/workspace.py

add initial value feature
fix bug.

Chassis modify

---

infrasim/model/core/task.py
infrasim/model/tasks/compute.py
requirements.txt
test/functional/test_ivn.py

user can specify a capture time during booting for stderr of qemu

compute: add capturing time for stderr of qemu during booting

---

test/functional/test_ivn.py

Added test to start node in namespace

Added test about start node in namespace

---

test/fixtures.py
test/functional/test_boot.py
test/functional/test_chassis.py
test/functional/test_configuration_change.py
test/functional/test_drive_error_inject.py
test/functional/test_host_io.py
test/functional/test_infrasim_monitor.py
test/functional/test_ipmi_chassis.py
test/functional/test_ipmi_console.py
test/functional/test_ipmi_kcs_smbios.py
test/functional/test_ipmi_sim_log.py
test/functional/test_ivn.py
test/functional/test_main_intf.py
test/functional/test_net_namespace.py
test/functional/test_node_ports.py
test/functional/test_nvme.py
test/functional/test_pcie_topo.py
test/functional/test_racadm.py
test/functional/test_sas.py
test/functional/test_scsi_page.py
test/functional/test_start_stop.py
test/functional/test_storage.py
test/functional/test_version_command.py
test/functional/test_with_bridge.py
tox.ini

1. Add "SKIP_TESTS" for PR triggered
2. Unify guest os to Ubuntu 16.04

Shorten PR triggered period

---

test/functional/test_ipmi_kcs_smbios.py

Cherry-pick Alan's commit which fixed the R630 smbios test issue.

Infrasim 4.0

---

infrasim/model/core/chassis.py

Add status error section in share memory for scsi/nvme device

---

test/functional/test_nvme_hotplug.py

support drive add/delete test for a known drive

add hot plug test for nvme drive

---

infrasim/model/core/chassis.py
infrasim/model/tasks/bmc.py
test/fixtures.py

Add shmkey in openipmi command line

---

test/functional/test_nvme_hotplug.py
tox.ini

Remove '--exe' in nosetests in tox.ini.

[Test PR] remove '--exe' in nosetests in tox.ini

---

infrasim/model/elements/pci_vmd.py
infrasim/model/elements/pcie_port.py
infrasim/model/elements/pcie_topology.py
test/fixtures.py
test/functional/test_ivn.py
test/functional/test_vmd.py

1. implement vmd device.
2. implement vmd test case using cloud image
3. define a macro to represent cloud img name.

implement vmd support 

---

infrasim/chassis/agent.py
infrasim/chassis/dataset.py
infrasim/chassis/share_memory.py
infrasim/model/core/chassis.py
infrasim/model/tasks/bmc.py
infrasim/workspace.py

Signed-off-by: Aaron Wei <aaron.wei@dell.com>

chassis: add nvme vpd and health data into sharememory

---

infrasim/sshclient.py
test/functional/test_ivn.py

1. add 10s delay for paramiko sshclient connection
2. Update ivn submodule
3. Refine test_ivn to remove cloudimgs folder at setup_module

add 10s delay for paramiko ssh connection

---

requirements.txt

requirements: change paramiko to 2.4.1

---

infrasim/sshclient.py
test/functional/test_nvme.py

1. Refine sshclient to print less trying to connect info
2. Refine test_nvme to make ssh as global variable

Refine sshclient and test_nvme

---

infrasim/model/elements/drive.py
test/functional/test_drive_sector.py

Sector 520

---

infrasim/model/core/chassis.py
infrasim/model/elements/backend.py
infrasim/model/elements/storage.py
infrasim/model/elements/storage_diskarray.py
infrasim/model/elements/storage_lsi.py
infrasim/model/elements/storage_pmc.py

1. generate topology and save to binary file.
2. in chassis start, load topology to sharememory.
3. move diskarray support code to storage.py, the base class of controller, in order to simplify the code.

diskarray: refactor and chenge implementation to share memory

---

infrasim/model/elements/storage_diskarray.py

fix 1. pad wrong number when processing expander list.
fix 2. failed to process drive when there is space in product name.

diskarray, fixbug

---

infrasim/package_manager.py
requirements.txt
test/functional/test_sas.py

1. Skip test_sas_chain and test_disk_directly for PR test
2. Add netifaces into requirements

Add skip test for lsi3008 sas chain test

---

test/functional/test_scsi_error_inject.py

Skip scsi error inject for PR test.

Skip scsi error inject for PR test

---

infrasim/model/tasks/compute.py
test/functional/test_chassis.py

bring ahead the processing of network.

add ntb test case

---

infrasim/cli.py

Node workspace can be destroyed even it has wrong yml.

cli: it can destroy workspace even yml is wrong

---

test/fixtures.py
test/functional/test_nvme.py
test/functional/test_scsi_page.py
test/functional/test_storage.py
test/functional/test_vmd.py

Update test image to Ubuntu 18.04

Update test image to Ubuntu 18.04

---

infrasim/chassis/__init__.py
infrasim/model/core/chassis.py
infrasim/model/elements/machine.py
infrasim/model/elements/network.py
template/vbmc.conf

add some missing field and implement feature of monitoring power status.

add missing field for project B.

---

test/functional/test_ipmi_kcs_smbios.py

Remove ssh connecting and ssh.close while sending each ipmi remote command

Update test ipmi kcs test

---

test-requirements.txt
tox.ini

add INFRASIM_ROOT to tox passenv

add INFRASIM_ROOT to tox passenv

---

infrasim/init.py
infrasim/model/core/node.py
infrasim/model/tasks/compute.py
template/infrasim.yml

1. add uuid while init infrasim and start node
2. handle uuid in yaml file

Add uuid parameter in infrasim node

---

infrasim/chassis/emu_data.py

Add functional load-from-file in chassis emu_data decode to handle fru.bin in node.emu
`mc_add_fru_data 0x20 0x00 0x1000 file 0 "/home/infrasim/infraim/fru.bin"`

Add load-from-file in chassis emu data decode

---

infrasim/model/tasks/bmc.py
infrasim/workspace.py
template/chassiscontrol
template/setbootcmd

add setbootcmd script to trigger save_bootdev in qemu

support bootorder config in compute

---

infrasim/model/core/task.py
infrasim/model/elements/cpu_binding.py
infrasim/model/elements/qemu_monitor.py
infrasim/model/tasks/compute.py

Implement cpu binding feature in CCompute

---

infrasim/model/tasks/bmc.py

For nvram data, try to get from workspace first then try from given path.

---

infrasim/model/tasks/compute.py

move forward '-uuid' to make qemu handle if before smbios

move forward '-uuid' to make qemu handle if before smbios

---

test/functional/test_uuid.py

add a test case to test qemu's uuid 
@chenge3  @XiaowenJiang  help to review

support uuid test

---

infrasim/model/elements/network.py

Add id attribute for NIC

---

infrasim/init.py
infrasim/model/elements/cpu_binding.py

Move update bridge config and link library out of skip installation

---

infrasim/sshclient.py
test/functional/test_link_change_error_inject.py
test/functional/test_nic_stat_error_inject.py
test/functional/test_serial_number.py

depending on https://eos2git.cec.lab.emc.com/InfraSIM/qemu/pull/141

add test script for vmxnet3 data error inject

---

infrasim/helper.py
infrasim/model/tasks/compute.py
test/functional/test_bmc_peer_communication.py
test/functional/test_cli_commands.py
test/functional/test_configuration_change.py
test/functional/test_node_ports.py
test/functional/test_storage.py
test/functional/test_with_bridge.py
test/unit/test_model.py

compute: save args of qemu to file

---

infrasim/chassis/emu_data.py
test/functional/test_chassis.py

1. keep layout of bin file unchanged.
2. save to file after data is ready.

emu_file. refactor code for safty and compatibility.
